services:
  postgres:
    container_name: postgres1
    image: postgres
    user: root
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ${BASE_PATH}/data/postgres:/var/lib/postgresql/data
      - ${BASE_PATH}/data/pgbckp:/pgbckp

  mongodb:
    container_name: mongodb1
    image: mongo
    hostname: mongodb
    volumes:
      - ${BASE_PATH}/scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ${BASE_PATH}/data/mongo:/data/
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"
      MONGO_INITDB_USER: "${MONGO_USER}"
      MONGO_INITDB_PWD: "${MONGO_PASSWORD}"
    ports:
      - 27017:27017
