name: CI Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres:alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_t_PASSWORD }}
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb
          POSTGRES_PORT: 5432
        ports: ["5432:5432"]
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run docker-compose / Init mongodb
        uses: hoverkraft-tech/compose-action@v2.0.1
#        with:
#          compose-file: "./apps/mongoose/docker-compose.yml"

#      - name: Build mongodb
#        run: docker-compose -f ./apps/mongoose/docker-compose.yml build

      - name: Init mongodb
        run: docker-compose -f ./apps/mongoose/docker-compose.yml up -d mongodb

      - name: Install Packages
        run: npm i

      - name: Npm run test
        run: npm run test
        env:
          NODE_ENV: test
          POSTGRES_URL: ${{ secrets.POSTGRES_t_URL }}
          MONGO_URL: ${{ secrets.MONGO_t_URL }}

