version: "3"

services:

  mongodb:
    container_name: mongodb
    image: mongo
    hostname: mongodb
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./data/mongo:/data/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=development
      - MONGO_INITDB_USER=mongodb
      - MONGO_INITDB_PWD=mongodb
    ports:
      - 27017:27017

  server:
    container_name: server
    image: nestjs-mongoose
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PORT: 3000
      MONGO_URL: mongodb://mongodb:mongodb@mongodb:27017/development
      JWT_SECRET_KEY: keyboard_cat
    depends_on:
      - mongodb
    links:
      - mongodb
